# Generated by Django 5.2.12 on 2026-03-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_booking_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetail',
            name='correction_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookingdetail',
            name='correction_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingdetail',
            name='correction_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingdetail',
            name='correction_token',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='bookingdetail',
            name='flagged_field_notes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='bookingdetail',
            name='flagged_fields',
            field=models.JSONField(blank=True, default=list, help_text='Field names flagged as incorrect by admin'),
        ),
    ]
