# Generated by Django 5.2.12 on 2026-03-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_correction_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='phone_country_code',
            field=models.CharField(default='+1', max_length=5),
        ),
        migrations.AddField(
            model_name='booking',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
