# Generated by Django 5.2.12 on 2026-03-20 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_add_state_and_phone_country_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingdetail',
            name='correction_completed',
        ),
        migrations.RemoveField(
            model_name='bookingdetail',
            name='correction_completed_at',
        ),
        migrations.RemoveField(
            model_name='bookingdetail',
            name='correction_requested_at',
        ),
        migrations.RemoveField(
            model_name='bookingdetail',
            name='correction_token',
        ),
        migrations.RemoveField(
            model_name='bookingdetail',
            name='flagged_field_notes',
        ),
        migrations.RemoveField(
            model_name='bookingdetail',
            name='flagged_fields',
        ),
    ]
