# Generated by Django 5.2.12 on 2026-03-20 18:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_guest_booking_nullable_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='form2_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='form2_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
