# Generated by Django 5.2.12 on 2026-04-13 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_set_db_defaults'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='assigned_admin',
            field=models.ForeignKey(blank=True, help_text='Admin responsible for this booking (used for booking-level chat).', limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
