# Generated by Django 5.2.12 on 2026-04-16 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_rename_booking_tok_user_id_is_used_idx_booking_tok_user_id_5e2a14_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bookingtoken',
            new_name='booking_tok_user_id_5e2a14_idx',
            old_name='booking_tok_user_id_is_used_idx',
        ),
        migrations.RenameIndex(
            model_name='bookingtoken',
            new_name='booking_tok_expires_c1d8ea_idx',
            old_name='booking_tok_expires_at_idx',
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
