# Generated by Django 5.2.12 on 2026-04-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_booking_work_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='work_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='work_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
