# Generated by Django 5.2.12 on 2026-04-23 12:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_booking_work_completed'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AstrologyBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_id', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_country_code', models.CharField(default='+1', max_length=5)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('special_note', models.TextField(blank=True, max_length=900)),
                ('ast_full_name', models.CharField(blank=True, max_length=255)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_time', models.TimeField(blank=True, null=True)),
                ('birth_time_not_sure', models.BooleanField(default=False)),
                ('birth_place', models.CharField(blank=True, max_length=255)),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('appointment_time', models.TimeField(blank=True, null=True)),
                ('additional_notes', models.TextField(blank=True)),
                ('form2_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('form2_submitted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('payment_pending', 'Payment Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='astrology_bookings', to='services.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='astrology_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Astrology Booking',
                'verbose_name_plural': 'Astrology Bookings',
                'db_table': 'astrology_bookings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='astrology_b_user_id_3edfb3_idx'), models.Index(fields=['booking_id'], name='astrology_b_booking_eeaca5_idx')],
            },
        ),
    ]
