# Generated by Django 5.2.12 on 2026-04-26 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0016_astrologybooking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AstrologyBooking',
        ),
    ]
