# Generated by Django 5.2.12 on 2026-04-17 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('CHAT', 'Chat Message'), ('PAYMENT', 'Payment Received'), ('BOOKING', 'New Booking'), ('CASE_UPDATE', 'Case Status Update'), ('PARTIAL_OVERDUE', 'Partial Payment Overdue'), ('ADMIN_ACTION', 'Admin Action Required'), ('SYSTEM', 'System Notification')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('case_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('booking_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('payment_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('order_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional data like amount, service name, etc.')),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(help_text='User who should receive this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'), models.Index(fields=['recipient', 'is_read', '-created_at'], name='notificatio_recipie_684eac_idx')],
            },
        ),
    ]
