# Generated by Django 5.2.12 on 2026-04-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        # Drop the old integer columns and recreate as UUID
        migrations.RunSQL(
            sql="""
                ALTER TABLE notifications_notification 
                DROP COLUMN booking_id,
                DROP COLUMN case_id,
                DROP COLUMN order_id,
                DROP COLUMN payment_id;
                
                ALTER TABLE notifications_notification
                ADD COLUMN booking_id UUID NULL,
                ADD COLUMN case_id UUID NULL,
                ADD COLUMN order_id UUID NULL,
                ADD COLUMN payment_id UUID NULL;
                
                CREATE INDEX IF NOT EXISTS notifications_notification_booking_id_idx ON notifications_notification(booking_id);
                CREATE INDEX IF NOT EXISTS notifications_notification_case_id_idx ON notifications_notification(case_id);
                CREATE INDEX IF NOT EXISTS notifications_notification_order_id_idx ON notifications_notification(order_id);
                CREATE INDEX IF NOT EXISTS notifications_notification_payment_id_idx ON notifications_notification(payment_id);
            """,
            reverse_sql="""
                ALTER TABLE notifications_notification 
                DROP COLUMN booking_id,
                DROP COLUMN case_id,
                DROP COLUMN order_id,
                DROP COLUMN payment_id;
                
                ALTER TABLE notifications_notification
                ADD COLUMN booking_id INTEGER NULL,
                ADD COLUMN case_id INTEGER NULL,
                ADD COLUMN order_id INTEGER NULL,
                ADD COLUMN payment_id INTEGER NULL;
                
                CREATE INDEX IF NOT EXISTS notifications_notification_booking_id_idx ON notifications_notification(booking_id);
                CREATE INDEX IF NOT EXISTS notifications_notification_case_id_idx ON notifications_notification(case_id);
                CREATE INDEX IF NOT EXISTS notifications_notification_order_id_idx ON notifications_notification(order_id);
                CREATE INDEX IF NOT EXISTS notifications_notification_payment_id_idx ON notifications_notification(payment_id);
            """
        ),
    ]
