# Generated by Django 5.2.12 on 2026-04-27 10:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0017_drop_astrology_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuraSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_email', models.EmailField(help_text='Client email address – copied from booking at creation time.', max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('link_sent', 'Link Sent'), ('booked', 'Booked')], db_index=True, default='pending', max_length=20)),
                ('session_link_token', models.CharField(blank=True, help_text='Secure token for the public scheduling link.', max_length=128, null=True, unique=True)),
                ('link_expiry', models.DateTimeField(blank=True, help_text='UTC datetime after which the link is considered expired.', null=True)),
                ('session_start', models.DateTimeField(blank=True, help_text='UTC start time of the confirmed session slot.', null=True)),
                ('session_end', models.DateTimeField(blank=True, help_text='UTC end time of the confirmed session slot.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(help_text='The aura/family-aura booking this session belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='aura_session', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Aura Session',
                'verbose_name_plural': 'Aura Sessions',
                'db_table': 'aura_sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='aura_sessio_status_944b2c_idx'), models.Index(fields=['session_link_token'], name='aura_sessio_session_b9582f_idx')],
            },
        ),
    ]
