# Generated by Django 5.2.12 on 2026-04-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aura_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aurasession',
            name='client_timezone',
            field=models.CharField(default='UTC', help_text='IANA timezone string auto-detected from client browser (e.g. "America/New_York").', max_length=100),
        ),
    ]
