# Generated by Django 5.2.12 on 2026-04-17 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfPasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Self Password Reset Token',
                'verbose_name_plural': 'Self Password Reset Tokens',
                'db_table': 'self_password_reset_tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token_hash'], name='self_passwo_token_h_be4974_idx'), models.Index(fields=['user', 'is_used'], name='self_passwo_user_id_f6010b_idx')],
            },
        ),
    ]
