# Generated by Django 5.2.12 on 2026-04-26 11:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0017_drop_astrology_booking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperAdminAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='UTC', help_text='IANA timezone string, e.g. "Asia/Kolkata"', max_length=100)),
                ('weekly_schedule', models.JSONField(default=dict, help_text='Dict keyed by lowercase weekday name, value = list of "HH:MM-HH:MM" strings')),
                ('session_duration', models.PositiveIntegerField(default=30, help_text='Session length in minutes')),
                ('cooldown_time', models.PositiveIntegerField(default=10, help_text='Gap between sessions in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'superadmin'}, on_delete=django.db.models.deletion.CASCADE, related_name='astrology_availability', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SuperAdmin Availability',
                'db_table': 'astrology_superadmin_availability',
            },
        ),
        migrations.CreateModel(
            name='AstrologySchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appointment_start', models.DateTimeField(help_text='UTC')),
                ('appointment_end', models.DateTimeField(help_text='UTC')),
                ('client_timezone', models.CharField(help_text='IANA timezone string provided by the client', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='astrology_schedule', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Astrology Schedule',
                'db_table': 'astrology_schedule',
                'indexes': [models.Index(fields=['appointment_start'], name='astrology_s_appoint_fceaea_idx'), models.Index(fields=['appointment_end'], name='astrology_s_appoint_4b7b27_idx')],
            },
        ),
    ]
