# Generated by Django 5.2.12 on 2026-04-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_can_manage_blogs'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='invitationtoken',
            new_name='invitation__token_adecf7_idx',
            old_name='invitation_token_idx',
        ),
        migrations.RenameIndex(
            model_name='invitationtoken',
            new_name='invitation__user_id_bea248_idx',
            old_name='invitation_user_type_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(choices=[('manual', 'Manual'), ('google', 'Google'), ('yahoo', 'Yahoo')], default='manual', max_length=20),
        ),
    ]
