# Generated by Django 5.2.12 on 2026-04-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_invitation_token_idx_invitation__token_adecf7_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_self_registered',
            field=models.BooleanField(default=False),
        ),
    ]
