# Generated by Django 5.2.12 on 2026-04-17 07:20

from django.db import migrations


def backfill_is_self_registered(apps, schema_editor):
    """
    Mark all existing self-registered users.

    Eligible: auth_provider in (manual, google, yahoo), not a guest,
    not a superadmin, AND not created via an admin invitation token.
    """
    User = apps.get_model('accounts', 'User')
    InvitationToken = apps.get_model('accounts', 'InvitationToken')

    # IDs of users who were invited/created by an admin
    admin_created_ids = set(
        InvitationToken.objects.filter(
            token_type='invite',
            created_by__isnull=False,
        ).values_list('user_id', flat=True)
    )

    updated = User.objects.filter(
        is_guest=False,
        auth_provider__in=['manual', 'google', 'yahoo'],
    ).exclude(
        role='superadmin',
    ).exclude(
        id__in=admin_created_ids,
    ).update(is_self_registered=True)

    print(f"  Backfilled is_self_registered=True for {updated} user(s).")


def reverse_backfill(apps, schema_editor):
    pass  # Irreversible — safe to leave as-is on rollback


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_self_registered_and_self_reset_token'),
    ]

    operations = [
        migrations.RunPython(backfill_is_self_registered, reverse_backfill),
    ]
