# Generated by Django 5.2.12 on 2026-04-11 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogimage',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.RenameIndex(
            model_name='blog',
            new_name='blogs_status_3796eb_idx',
            old_name='blog_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='blog',
            new_name='blogs_slug_ec41d2_idx',
            old_name='blog_slug_idx',
        ),
        migrations.AddField(
            model_name='blog',
            name='poster_image_alt',
            field=models.CharField(blank=True, help_text='Alt text for the poster image (SEO)', max_length=255),
        ),
    ]
