# Generated by Django 5.2.12 on 2026-04-13 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_rename_booking_tok_user_id_is_used_idx_booking_tok_user_id_5e2a14_idx_and_more'),
        ('cases', '0003_update_sales_case_sources'),
        ('chat', '0002_casemessage_conversation_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='casemessage',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='casemessage',
            name='source_type',
            field=models.CharField(choices=[('CASE', 'Case Thread'), ('BOOKING', 'Booking Thread')], db_index=True, default='CASE', help_text='CASE = case-level thread; BOOKING = booking-level admin-only thread.', max_length=10),
        ),
        migrations.AlterField(
            model_name='casemessage',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='cases.case'),
        ),
        migrations.AddIndex(
            model_name='casemessage',
            index=models.Index(fields=['booking', 'created_at'], name='case_messag_booking_d81a3d_idx'),
        ),
    ]
