# Generated by Django 5.0.3 on 2026-03-11 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_multi_gateway_support'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_gateway_e04247_idx',
            old_name='payments_gateway_payment_id_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_gateway_3ac0c5_idx',
            old_name='payments_gateway_status_idx',
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway_request',
            field=models.JSONField(blank=True, help_text='Raw request payload sent to the gateway', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway_response',
            field=models.JSONField(blank=True, help_text='Raw response received from the gateway', null=True),
        ),
    ]
