# Generated by Django 5.2.12 on 2026-04-16 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_salesorder_partial_since'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='salesquote',
            new_name='sales_quote_access__ca3b8d_idx',
            old_name='sales_quote_access_token_idx',
        ),
    ]
