# Generated by Django 5.2.12 on 2026-04-16 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_booking_work_completed'),
        ('cases', '0003_update_sales_case_sources'),
        ('sales', '0004_rename_sales_quote_access_token_idx_sales_quote_access__ca3b8d_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesquote',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='bookings.booking'),
        ),
        migrations.AlterField(
            model_name='salesquote',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='cases.case'),
        ),
    ]
